# Generated by Django 2.2.10 on 2020-06-11 01:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(default=25.54)),
                ('fecha', models.DateField(default=datetime.datetime(2020, 6, 11, 1, 16, 25, 295949, tzinfo=utc))),
            ],
        ),
    ]
