# Generated by Django 2.2.10 on 2020-06-13 03:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_iot', '0002_auto_20200611_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Asuncion', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='medida',
            name='fecha',
            field=models.CharField(default=datetime.datetime(2020, 6, 13, 3, 10, 40, 411892), max_length=50),
        ),
        migrations.AddField(
            model_name='medida',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='data_iot.Ciudad'),
        ),
    ]
