# Generated by Django 2.2.10 on 2020-06-17 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_iot', '0002_auto_20200614_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_disp', models.CharField(default='0', max_length=50)),
                ('token', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='medida',
            name='fecha',
            field=models.CharField(default=datetime.datetime(2020, 6, 17, 0, 21, 55, 408623), max_length=50),
        ),
    ]
