# Generated by Django 2.2.10 on 2020-06-13 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_iot', '0005_auto_20200613_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medida',
            name='fecha',
            field=models.CharField(default=datetime.datetime(2020, 6, 13, 3, 57, 4, 991156), max_length=50),
        ),
    ]
