# Generated by Django 2.2.10 on 2020-06-14 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_iot', '0006_auto_20200613_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medida',
            name='codigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data_iot.Codigo'),
        ),
        migrations.AlterField(
            model_name='medida',
            name='fecha',
            field=models.CharField(default=datetime.datetime(2020, 6, 14, 18, 58, 10, 909799), max_length=50),
        ),
    ]
